name: Block merge on design-freeze label

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize]

jobs:
  guard:
    if: contains(github.event.pull_request.labels.*.name, 'design-freeze')
    runs-on: ubuntu-latest
    steps:
      - name: Fail when design-freeze present
        run: |
          echo "PR is under design-freeze. Remove the label before merging."
          exit 1
